version: "3.9"

services:
  wafi-worker:
    image: swilltec/wafi-worker
    build:
      context: .
      dockerfile: ./worker/Dockerfile   
    env_file:
      - .env
    container_name: wafi-worker
    restart: "on-failure"
    network_mode: host

  wafi-starter:
    image: swilltec/wafi-starter
    build:
      context: .
      dockerfile: ./starter/Dockerfile   
    env_file:
      - .env
    container_name: wafi-starter
    restart: "on-failure"
    network_mode: host
