apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: temporal-admin-tools
  name: temporal-admin-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: temporal-admin-tools
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/temporal-network: "true"
        io.kompose.service: temporal-admin-tools
    spec:
      containers:
        - env:
            - name: TEMPORAL_CLI_ADDRESS
              value: temporal:7233
          image: temporalio/admin-tools:1.20.0
          name: temporal-admin-tools
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
